import Head from 'next/head';
import Layout from '@/components/Layout';
import Image from 'next/image';
import profilePic from '../../public/images/profile/developer-pic-4.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkDownload } from '@/components/Icons';
import HireMe from '@/components/HireMe';

export default function Home() {
	return (
		<>
			<Head>
				<title>Anna Li</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
				<Layout className='pt-0 md:p-16 sm:pt-8'>
					<div className='flex items-center justify-center w-full lg:flex-col'>
						<div className='w-1/3 xl:w-1/3 lg:w-1/2 md:w-1/2'>
							<Image
								src={profilePic}
								alt='image'
								className='w-full h-auto md:inline-block md:w-full'
								priority
								sizes='(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw'
							></Image>
						</div>
						<div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
							<p className='my-4 text-base font-medium'>Hey, I am Anna</p>
							<AnimatedText
								text='Turning Vision Into Reality With Code And Design.'
								className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text=6xl md:!text-5xl sm:!text-3xl'
							/>
							<p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
								As a skilled full-stack developer, I am dedicated to turning
								ideas into innovative web applications. I am well-versed in a
								variety of technologies. My continuous learning keeps me updated
								with the latest technologies and enables me to deliver
								innovative solutions to complex problems.
							</p>
							<div className='flex items-center self-center mt-2 lg:self-center'>
								<Link
									href='/Anna Li-Resume.pdf'
									target='_blank'
									className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light md:p-2 md:px-4 md:text-base'
									download={true}
								>
									Resume <LinkDownload className='w-6 ml-1 dark:text-dark' />
								</Link>
								<Link
									href='mailto:annalideveloper@gmail.com'
									target='_blank'
									className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base'
								>
									Contact
								</Link>
							</div>
						</div>
					</div>
				</Layout>
				<HireMe />
			</main>
		</>
	);
}
